# the default dev override file

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - frontend_dev:/usr/src/app/node_modules
  backend:
    env_file:
      - backend/envs/dev.env
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - backend_dev:/usr/src/app/.venv
  db:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
volumes:
  backend_dev:
  frontend_dev:
