services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
  backend:
    env_file:
      - backend/envs/live.env
    build:
      dockerfile: Dockerfile.prod
  nginx:
    build:
      dockerfile: Dockerfile.live
