"""add is_moderator to user model

Revision ID: 1743206591
Revises: 1740940966
Create Date: 2025-03-29 00:03:12.233395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1743206591'
down_revision: Union[str, None] = '1740940966'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('posts', 'id',
    #            existing_type=sa.UUID(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    op.add_column('user', sa.Column('is_moderator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_moderator')
    # op.alter_column('posts', 'id',
    #            existing_type=sa.Integer(),
    #            type_=sa.UUID(),
    #            existing_nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
