"""Add missing report fields

Revision ID: 1743388771
Revises: 1743289688
Create Date: 2025-03-31 02:39:31.702529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1743388771'
down_revision: Union[str, None] = '1743289688'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('reason', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'resolved_at')
    op.drop_column('reports', 'reason')
    # ### end Alembic commands ###
