"""added report model

Revision ID: 1743274596
Revises: 1743206591
Create Date: 2025-03-29 18:56:36.359992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1743274596'
down_revision: Union[str, None] = '1743206591'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reportee_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reportee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('posts', 'id',
    #            existing_type=sa.UUID(),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('posts', 'id',
    #            existing_type=sa.Integer(),
    #            type_=sa.UUID(),
    #            existing_nullable=False,
    #            autoincrement=True,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_table('reports')
    # ### end Alembic commands ###
