name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Unlock Git Crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git crypt unlock -
          touch crypt/unlocked
      
      - name: Set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIVE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "watconf.kabir.dev ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlz6kMlk+/MJTtl0uYOElD3pk6MWCfURDaVfPvQzw1c" >> ~/.ssh/known_hosts
          ssh -q me@watconf.kabir.dev exit

      - name: Deploy
        run: make deploy
