name: Test Backend

on: [push]

jobs:
  test_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unlock Git Crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64 -d | git crypt unlock -
          touch crypt/unlocked

      - name: Run Tests
        run: make test
